config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about'
  resources :post_images do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
    :email,
    :name,
    :postcode,
    :prefecture_name,
    :address_city,
    :address_street,
    :address_building])
  # 　devise_parameter_sanitizer.permit(:sign_in, keys: [:name,:passward])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end

  private
   def post_comment_params
     params.require(:post_comment).permit(:comment)
   end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :authenticate_user!
  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
    @post_images = PostImage.page(params[:page]).reverse_order
    @users = User.all
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post_image = PostImage.find(params[:id])
  end

  def update
    @post_image = PostImage.find(params[:id])
    @post_image.update(post_image_params)
    redirect_to post_image_path
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private
  def post_image_params
    params.require(:post_image).permit(:picture_name, :image, :caption, :title )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

   private
   def post_image_params
    params.require(:post_image).permit(:picture_name, :image, :caption, :title )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<div class="header-message">
  <h2 class="header-word">Do you like FootBall ?</h2>
  <%= image_tag 'adidas.jpg', class: 'header-picture' %>
</div>

<div class="header-message">
  <h2 class="header-word">Who is your favorite player ?</h2>
  <%= image_tag 'messi.jpg', class: 'player-picture' %>
  <%= image_tag 'ronaudo.jpg', class: 'player-picture' %>
  <%= image_tag 'neymar.jpg', class: 'player-picture' %>
</div>

<div class="header-message">
  <h2 class="header-word">Which team do you support ?</h2>
   <%= image_tag 'list.jpg', class: 'team-picture' %>
</div>

<div class="header-message">
  <h2 class="header-word">When is the most memorable moment ?</h2>
  <%= image_tag 'stars.jpg', class: 'memory-picture' %>
</div>

<div class="header-message">
<h1>Let's share your memory with us !!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WLF</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="header-container">
  <p class="header-title">
    <strong>WLF</strong>
  </p>

    <ul>
    <% if user_signed_in? %>
    <li class="header-logo">
      <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </li>

    <li class="header-logo">
      <%= link_to "Post", new_post_image_path %>
    </li>

     <li class="header-logo">
      <%= link_to "Usrs", users_path %>
    </li>

    <li class="header-logo">
      <%= link_to "Home", post_images_path %>
    </li>

    <% else %>

    <li class="header-logo">
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>

    <li class="header-logo">
      <%= link_to "Log In", new_user_session_path %>
    </li>

    <li class="header-logo">
      <%= link_to "Top", root_path %>
    <% end %>
    </li>
    </ul>
</div>

<div class="cover-all">
  <div class="cover-middle">

    <%= yield %>

  </div>
</div>
  </body>
</html>

app/views/post_images/edit.html.erb
<h1>Edit</h1>

<%= form_with model:@post_image, local:true do |f| %>
 <div>
 <%= f.attachment_field :image %>
 </div>

 <div>
 <%= f.text_field :picture_name, placeholder:"Title" %>
 </div>

 <div>
 <%= f.text_area :caption, placeholder:"Comment" %>
 </div>

<div>
<%= f.submit "Post"%>
</div>

<% end %>

app/views/post_images/index.html.erb
<h1>We Love FootBall</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>picture</th>
      <th>Title</th>
      <th>Caption</th>
    </tr>
  </thead>
  <tbody>
<% @post_images.each do |post_image| %>
  <tr>
  <td>
  <%= post_image.user.name %>
  </td>

  <td>
    <%= attachment_image_tag post_image, :image, :fill, 100, 100, format: 'jpeg' %>
  </td>

  <td>
    <%= post_image.picture_name %>
  </td>

  <td>
    <%= post_image.caption %>
  </td>

  <td>
    <%= link_to "#{post_image.post_comments.count} Comments", post_image_path(post_image.id) %>
  </td>

  <td>
    <%= link_to "Show", post_image_path(post_image) %>
  </td>
  </tr>
<% end %>
<%= paginate @post_images %>
</tbody>
</table>

app/views/post_images/new.html.erb
<h1>New Post</h1>
<%= form_with model:@post_image, local:true do |f| %>
 <div>
 <%= f.attachment_field :image %>
 </div>

 <div>
 <%= f.text_field :picture_name, placeholder:"Title" %>
 </div>

 <div>
 <%= f.text_area :caption, placeholder:"Comment" %>
 </div>

<div>
<%= f.submit "Post"%>
</div>

<% end %>

app/views/post_images/show.html.erb
<h1>Posts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
  <tr>

   <td>
    <%= @post_image.user.name %>
  </td>

  <td>
    <%= attachment_image_tag @post_image, :image, :fill, 100, 100, format: 'jpeg' %>
  </td>

  <td>
    <%= @post_image.picture_name %>
  </td>

  <td><%= @post_image.post_comments.count %>Comments</td>

  <td>
  <% if @post_image.favorited_by?(current_user) %>
    <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= @post_image.favorites.count %> Goods
    <% end %>
  </td>
  <td>
  <% else %>
    <%= link_to post_image_favorites_path(@post_image), method: :post do %>
     <i class="fa fa-heart-o" aria-hidden="true"></i>
     <%= @post_image.favorites.count %> Goods
  <% end %>
  </td>
<% end %>

  <td>
    <%= link_to "Edit", edit_post_image_path(@post_image) %>
  </td>

  <td>
    <%= link_to "Destroy", post_image_path(@post_image), method: :delete %>
  </td>
  </tr>
  </tbody>
</table>

<ol>
  <% @post_image.post_comments.each do |post_comment| %>
  <div><%= attachment_image_tag @user, :profile_image_id, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></div>
  <div><%= post_comment.user.name %></div>
  <span><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
  <div><%= post_comment.comment %></div>

  <% if post_comment.user == current_user %>
  <div>
    <%= link_to "Destroy", post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, class: "btn btn-danger" %>
  </div>
  <% end %>
  <% end %>
</ol>

<%= form_with(model:[@post_image, @post_comment], local: true) do |f| %>
<%= f.text_area :comment, rows:"5", class: "form-control", placeholder: "Comment" %>
<%= f.submit "Send", class: "btn btn-lg  pull-right" %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.name %>
      </td>

      <td>
        <%= attachment_image_tag user, :profile_image_id, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
      </td>

      <td>
        <%= link_to "Show", user_path(user.id) %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>We Love FootBall</h1>

<table class="table table-hover">
  <thead>
    <tr>
    <th>Name</th>
    <th>Picture</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>
        <%= @user.name %>
      </td>

      <td>
        <%= attachment_image_tag @user, :profile_image_id, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>
      </td>

      <td>
        <%= link_to "Édit", "#" %>
      </td>
    </tr>
</tbody>
</table>